wget -P pohoda-schema/ \
  https://www.stormware.cz/xml/schema/version_2/accountancy.xsd \
  https://www.stormware.cz/xml/schema/version_2/accountingunit.xsd \
  https://www.stormware.cz/xml/schema/version_2/actionPrice.xsd \
  https://www.stormware.cz/xml/schema/version_2/addressbook.xsd \
  https://www.stormware.cz/xml/schema/version_2/balance.xsd \
  https://www.stormware.cz/xml/schema/version_2/bank.xsd \
  https://www.stormware.cz/xml/schema/version_2/bankAccount.xsd \
  https://www.stormware.cz/xml/schema/version_2/cashRegister.xsd \
  https://www.stormware.cz/xml/schema/version_2/category.xsd \
  https://www.stormware.cz/xml/schema/version_2/contract.xsd \
  https://www.stormware.cz/xml/schema/version_2/data.xsd \
  https://www.stormware.cz/xml/schema/version_2/documentresponse.xsd \
  https://www.stormware.cz/xml/schema/version_2/enquiry.xsd \
  https://www.stormware.cz/xml/schema/version_2/filter.xsd \
  https://www.stormware.cz/xml/schema/version_2/groupStocks.xsd \
  https://www.stormware.cz/xml/schema/version_2/individualPrice.xsd \
  https://www.stormware.cz/xml/schema/version_2/intDoc.xsd \
  https://www.stormware.cz/xml/schema/version_2/intParam.xsd \
  https://www.stormware.cz/xml/schema/version_2/inventoryLists.xsd \
  https://www.stormware.cz/xml/schema/version_2/invoice.xsd \
  https://www.stormware.cz/xml/schema/version_2/list.xsd \
  https://www.stormware.cz/xml/schema/version_2/list_addBook.xsd \
  https://www.stormware.cz/xml/schema/version_2/list_contract.xsd \
  https://www.stormware.cz/xml/schema/version_2/list_stock.xsd \
  https://www.stormware.cz/xml/schema/version_2/mKasa.xsd \
  https://www.stormware.cz/xml/schema/version_2/numericalSeries.xsd \
  https://www.stormware.cz/xml/schema/version_2/offer.xsd \
  https://www.stormware.cz/xml/schema/version_2/order.xsd \
  https://www.stormware.cz/xml/schema/version_2/parameter.xsd \
  https://www.stormware.cz/xml/schema/version_2/payment.xsd \
  https://www.stormware.cz/xml/schema/version_2/prevodka.xsd \
  https://www.stormware.cz/xml/schema/version_2/prijemka.xsd \
  https://www.stormware.cz/xml/schema/version_2/print.xsd \
  https://www.stormware.cz/xml/schema/version_2/prodejka.xsd \
  https://www.stormware.cz/xml/schema/version_2/sendEET.xsd \
  https://www.stormware.cz/xml/schema/version_2/stock.xsd \
  https://www.stormware.cz/xml/schema/version_2/storage.xsd \
  https://www.stormware.cz/xml/schema/version_2/store.xsd \
  https://www.stormware.cz/xml/schema/version_2/supplier.xsd \
  https://www.stormware.cz/xml/schema/version_2/type.xsd \
  https://www.stormware.cz/xml/schema/version_2/voucher.xsd \
  https://www.stormware.cz/xml/schema/version_2/vydejka.xsd \
  https://www.stormware.cz/xml/schema/version_2/vyroba.xsd
